# Generated by Django 3.0.1 on 2019-12-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWallet', '0007_auto_20181230_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transfer')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transfer'), (4, 'Reconcile')]),
        ),
    ]
